Added Spring Cloud Sleuth for distributed log tracing.
GESoftware-CF/uaa pull request #256
Opened 2021-08-13 19:36 UTC by irinaepshteyn

That enables Predix Spring Log Filter to populate the 'corr' field of the log using the 'traceId' attribute of the SLF4J MDC: https://github.com/predix/spring-log-filter/commit/49d6ecda23ca50845fc7e0e74b4c5a1f8b2ef2d8. Reference: https://cloud.spring.io/spring-cloud-sleuth/reference/html/#sleuth-adding-project

2021-08-19 08:32 UTC, metacubed requested changes

2021-08-19 08:32 UTC, metacubed commented on server/src/main/java/org/cloudfoundry/identity/uaa/web/UaaLogFilter.java
> +        response.setHeader(CORRELATION_HEADER_NAME, correlationId);
Do we need to add a response header? It is not part of the tracing standard, just something custom we used to do.

2021-08-19 08:32 UTC, metacubed commented on server/src/main/java/org/cloudfoundry/identity/uaa/web/UaaLogFilter.java
> +            clearMDC();
(minor) Rename this to `clearCorrelationId` to match `setCorrelationId `?

2021-08-19 08:32 UTC, metacubed commented on server/src/main/java/org/cloudfoundry/identity/uaa/web/UaaLogFilter.java
> +            correlationId = UUID.randomUUID().toString();
This does not match the expected trace-id format. Check the trace-ids created by CF/AVI.

2021-08-19 08:32 UTC, metacubed commented on server/src/main/java/org/cloudfoundry/identity/uaa/web/UaaLogFilter.java
> +                     final String defaultZone) {
(minor) Whitespace

2021-08-19 18:12 UTC, akarollil commented
Pushkaraj gave me background info for this. I don't understand it enough :), but guess after upgrade to 75.0.0, we tried removing code (https://github.com/predix/spring-log-filter/commit/6087cfc668d3e2b7d8a25d74ded82cfff3ff2693) that added the correlation ID hoping that Spring Sleuth (added/enabled in 75.0.0?) will take care of it for us? But it doesn't in some cases because UAA isn't fully spring-booted :D. So this commit is bringing in that customization but by extending spring-log-filter?

I had some comments about the commit message. I tend to follow guidelines mentioned in https://chris.beams.io/posts/git-commit/. So if we follow that, the commit message could be something like what is below. Subject line limited to 50 characters. A blank link separating subject and body. Body lines wrapped at 72. Title/subject should ideally be about what the commit achieves maybe? We used to have distributed log tracing, but it went away after upgrade changes in some cases?

```
Fix missing correlation ID in log messages

Add distributed log tracing. In addition to Predix Spring Log Filter, it
enables UAA to populate the corr field of the log using the 'traceId'
attribute of the SLF4J MDC: predix/spring-log-filter@49d6ecd.

Note, spring-cloud-sleuth (Reference:
https://cloud.spring.io/spring-cloud-sleuth) doesn't seem to do this as
expected. Since UAA is "spring boot wannabe", sleuth doesn't correctly
instrument UAA beans for distributed tracing. Spring-cloud-sleuth is
boot based and only works with spring boot applications.

```

2021-08-20 18:35 UTC, irinaepshteyn commented
@metacubed, @akarollil, implemented requested changes.  Please review again.

2021-08-20 18:39 UTC, akarollil commented
Looks good to me, I will let Pushkaraj approve.

2021-08-20 18:42 UTC, metacubed approved these changes

2021-08-20 20:41 UTC, merged