Remove nurego spring profile from running SpringMeteringFilterIT Test
GESoftware-CF/uaa pull request #541
Opened 2023-02-17 06:28 UTC by Yogeshkumarb57

2023-02-18 00:13 UTC, irinaepshteyn requested changes
@Yogeshkumarb57, done reviewing. Please address my comments.

Also, in the commit comment it would be better to reference spring documentation for specific string version used by UAA. Current spring version as per [dependencies.gradle#L19](https://github.com/GESoftware-CF/uaa/blob/rc_75.18.3/dependencies.gradle#L19) is 5.3.18. Please change the spring doc reference to https://docs.spring.io/spring-framework/docs/5.3.18/reference/html/testing.html#integration-testing-annotations-meta

2023-02-18 00:13 UTC, irinaepshteyn commented on uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SpringMeteringFilterIT.java
> +@IfProfileValue(name = "spring.profiles.active", value = "nurego")
Requirement is to execute metering test if active profiles **contains** `nurego`.  For example, if `spring.profiles.active` is set to multiple values as before "default,nurego".  Will using `@IfProfileValue` satisfy that requirement? Please confirm

`spring.profiles.active=deafult, nurego` - Test should execute
`spring.profiles.active=nurego` - Test should execute
`spring.profiles.active=deafult` - Test should NOT execute
`spring.profiles.active=deafult, some-other-profile` - Test should NOT execute

2023-02-21 11:54 UTC, Yogeshkumarb57 commented
> @Yogeshkumarb57, done reviewing. Please address my comments.
> 
> Also, in the commit comment it would be better to reference spring documentation for specific string version used by UAA. Current spring version as per [dependencies.gradle#L19](https://github.com/GESoftware-CF/uaa/blob/rc_75.18.3/dependencies.gradle#L19) is 5.3.18. Please change the spring doc reference to https://docs.spring.io/spring-framework/docs/5.3.18/reference/html/testing.html#integration-testing-annotations-meta

Done

2023-02-23 04:49 UTC, irinaepshteyn approved these changes

2023-02-23 12:10 UTC, merged