Add stage changes
GESoftware-CF/uaa pull request #559
Opened 2023-04-20 08:57 UTC by rahul-3993

2023-04-20 23:46 UTC, irinaepshteyn requested changes
@rahul-3993 , please make commit message more verbose explaining why you are making this change.  For example: 

Add 'stage' to environment choices of EKS acceptance test pipeline

2023-04-24 20:29 UTC, irinaepshteyn commented
@rahul-3993 , please rebase your commit on top of https://github.com/GESoftware-CF/uaa/tree/predix_extensions_75.18.1 branch.

2023-04-25 16:29 UTC, johnson-jeb approved these changes

2023-04-25 17:12 UTC, irinaepshteyn approved these changes

2023-04-25 17:17 UTC, merged